version: "3.4"
services:
  projectathon6-consent_extraction:
    build: .
    volumes:
      - ./Ergebnisse:/Ergebnisse
      - ./config.R:/config.R
#      - ./localca.pem:/usr/local/share/ca-certificates/localca.crt
    image: "projectathon6-consent_extraction"  
